### PR TITLE
Update 06_energy_proportionality.png

### PR DESCRIPTION
**Pull request by childotg**
fixed typo in the meantime we discuss item #141

### CODE REVIEW

**Comment by childotg** [comment]
Pardon I committed on main, keep just the 9889098 for the PR

**Comment by holanita** [comment]
@greenhsu123 pls review. thank you.

**Comment by greenhsu123** [comment]
@childotg, thanks a lot for your PR; as mentioned in this [comment](https://github.com/Green-Software-Foundation/training/issues/141#issuecomment-1372674591), we would also like to update the y-axis's heading.

@holanita will work with the foundation's pm to update the image with the proposed changes.

Moreover, we will require a bit more time to review the Italian content. We cannot merge the Italian images as of now, but thanks a lot for doing it for us; we are really looking forward to having the Italian content asap!

**Comment by holanita** [comment]
The image has been fixed: https://learn.greensoftware.foundation/energy-efficiency/#energy-proportionality

**Pull request closed without merging**
